### ISSUE TITLE
Project checklist

### ISSUE THREAD

**Issue by KaanKalmi** [KaanKalmi/your-tribe-for-life-squad-page#15]
- [ ] Figma ontwerp maken
- [ ] Project klaar zetten
- [ ] Webpage layout maken
- [ ] Intro animatie (dat busje) maken
- [ ] De kaartjes invullen met data (van de studenten)
- [ ] Tijd over? Maak een pagina tussen de animatie en studenten in waar je kan kiezen welk pakket je wilt (squad keuze pagina)
